/************** TABLA peliculas ***************/

/*##################################################################
Definición de tabla peliculas y datos de prueba
####################################################################*/
CREATE SEQUENCE peliculas_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE peliculas(
   id INT GENERATED BY DEFAULT AS SEQUENCE peliculas_id_seq,
   titulo VARCHAR(300),
   fecha_estreno DATE,
   calificacion VARCHAR(100),   
   PRIMARY KEY(id)
);

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'El gran Lebowski', '1996-01-18','R');

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'No es pais para viejos', '2007-11-21','R');

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'En realidad, nunca estuviste aquí', '2017-05-27','R');
 
INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'Predestinación', '2015-01-09','R');

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'Voraz', '2016-04-14','R');

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'Coherencia', '2013-09-19','NR');

INSERT INTO peliculas(id, titulo, fecha_estreno,calificacion)
VALUES(DEFAULT,'Stalker', '1979-04-01','NR');



/*##################################################################
Definición de tabla generos y datos de prueba
####################################################################*/
CREATE SEQUENCE generos_id_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE generos(
   id INT GENERATED BY DEFAULT AS SEQUENCE generos_id_seq,
   nombre VARCHAR(300),
   PRIMARY KEY(id) 
);

INSERT INTO generos(id,nombre) VALUES(DEFAULT,'Terror');
INSERT INTO generos(id,nombre) VALUES(DEFAULT,'Ciencia ficción');
INSERT INTO generos(id,nombre) VALUES(DEFAULT,'Suspenso');
INSERT INTO generos(id,nombre) VALUES(DEFAULT,'Drama');
INSERT INTO generos(id,nombre) VALUES(DEFAULT,'Comedia');



/*##################################################################
tabla para relación MUCHOS A MUCHOS entre pelculas y generos 
####################################################################*/

CREATE TABLE peliculas_generos(
   id_pelicula INT,
   id_genero INT,
   PRIMARY KEY(id_pelicula,id_genero),
   FOREIGN KEY(id_pelicula) REFERENCES peliculas,
   FOREIGN KEY(id_genero) REFERENCES generos 
);

INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(1,5);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(2,3);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(3,3);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(3,4);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(4,2);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(4,3);
INSERT INTO peliculas_generos(id_pelicula,id_genero) 
VALUES(5,1);

